package com.worksap.kryotest.classes;

public class NullPrimitiveClass {

    int number1;
    int number2;
    int number3;
    int number4;
    int number5;
    int number6;
    int number7;
    int number8;
    int number9;
    int number10;
    int number11;
    int number12;
    int number13;
    int number14;
    int number15;
    int number16;
    int number17;
    int number18;
    int number19;
    int number20;
    int number21;
    int number22;
    int number23;
    int number24;
    int number25;
    long number26;
    long number27;
    long number28;
    long number29;
    long number30;
    long number31;
    long number32;
    long number33;
    long number34;
    long number35;
    long number36;
    long number37;
    long number38;
    long number39;
    long number40;
    long number41;
    long number42;
    long number43;
    long number44;
    long number45;
    long number46;
    long number47;
    long number48;
    long number49;
    long number50;
    int number51;
    int number52;
    int number53;
    int number54;
    int number55;
    int number56;
    int number57;
    int number58;
    int number59;
    int number60;
    int number61;
    int number62;
    int number63;
    int number64;
    int number65;
    int number66;
    int number67;
    int number68;
    int number69;
    int number70;
    int number71;
    int number72;
    int number73;
    int number74;
    int number75;
    long number76;
    long number77;
    long number78;
    long number79;
    long number80;
    long number81;
    long number82;
    long number83;
    long number84;
    long number85;
    long number86;
    long number87;
    long number88;
    long number89;
    long number90;
    long number91;
    long number92;
    long number93;
    long number94;
    long number95;
    long number96;
    long number97;
    long number98;
    long number99;
    long number100;

    String string1 = null;
    String string2 = null;
    String string3 = null;
    String string4 = null;
    String string5 = null;
    String string6 = null;
    String string7 = null;
    String string8 = null;
    String string9 = null;
    String string10 = null;
    String string11 = null;
    String string12 = null;
    String string13 = null;
    String string14 = null;
    String string15 = null;
    String string16 = null;
    String string17 = null;
    String string18 = null;
    String string19 = null;
    String string20 = null;
    String string21 = null;
    String string22 = null;
    String string23 = null;
    String string24 = null;
    String string25 = null;
    String string26 = null;
    String string27 = null;
    String string28 = null;
    String string29 = null;
    String string30 = null;
    String string31 = null;
    String string32 = null;
    String string33 = null;
    String string34 = null;
    String string35 = null;
    String string36 = null;
    String string37 = null;
    String string38 = null;
    String string39 = null;
    String string40 = null;
    String string41 = null;
    String string42 = null;
    String string43 = null;
    String string44 = null;
    String string45 = null;
    String string46 = null;
    String string47 = null;
    String string48 = null;
    String string49 = null;
    String string50 = null;

    @Override
    public String toString() {
        return string33 + "##" + number90;
    }

    public void changeValues() {
        this.string33 = "NONONOBOB";
        this.number90 = 1090123;
    }
}
