package com.worksap.kryotest.classes.heavy;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

public class NullHeavyClass {

    Integer number1 = null;
    Integer number2 = null;
    Integer number3 = null;
    Integer number4 = null;
    Integer number5 = null;
    Integer number6 = null;
    Integer number7 = null;
    Integer number8 = null;
    Integer number9 = null;
    Integer number10 = null;
    Integer number11 = null;
    Integer number12 = null;
    Integer number13 = null;
    Integer number14 = null;
    Integer number15 = null;
    Integer number16 = null;
    Integer number17 = null;
    Integer number18 = null;
    Integer number19 = null;
    Integer number20 = null;
    Integer number21 = null;
    Integer number22 = null;
    Integer number23 = null;
    Integer number24 = null;
    Integer number25 = null;
    Long number26 = null;
    Long number27 = null;
    Long number28 = null;
    Long number29 = null;
    Long number30 = null;
    Long number31 = null;
    Long number32 = null;
    Long number33 = null;
    Long number34 = null;
    Long number35 = null;
    Long number36 = null;
    Long number37 = null;
    Long number38 = null;
    Long number39 = null;
    Long number40 = null;
    Long number41 = null;
    Long number42 = null;
    Long number43 = null;
    Long number44 = null;
    Long number45 = null;
    Long number46 = null;
    Long number47 = null;
    Long number48 = null;
    Long number49 = null;
    Long number50 = null;
    BigDecimal number51 = null;
    BigDecimal number52 = null;
    BigDecimal number53 = null;
    BigDecimal number54 = null;
    BigDecimal number55 = null;
    BigDecimal number56 = null;
    BigDecimal number57 = null;
    BigDecimal number58 = null;
    BigDecimal number59 = null;
    BigDecimal number60 = null;
    BigDecimal number61 = null;
    BigDecimal number62 = null;
    BigDecimal number63 = null;
    BigDecimal number64 = null;
    BigDecimal number65 = null;
    BigDecimal number66 = null;
    BigDecimal number67 = null;
    BigDecimal number68 = null;
    BigDecimal number69 = null;
    BigDecimal number70 = null;
    BigDecimal number71 = null;
    BigDecimal number72 = null;
    BigDecimal number73 = null;
    BigDecimal number74 = null;
    BigDecimal number75 = null;
    BigInteger number76 = null;
    BigInteger number77 = null;
    BigInteger number78 = null;
    BigInteger number79 = null;
    BigInteger number80 = null;
    BigInteger number81 = null;
    BigInteger number82 = null;
    BigInteger number83 = null;
    BigInteger number84 = null;
    BigInteger number85 = null;
    BigInteger number86 = null;
    BigInteger number87 = null;
    BigInteger number88 = null;
    BigInteger number89 = null;
    BigInteger number90 = null;
    BigInteger number91 = null;
    BigInteger number92 = null;
    BigInteger number93 = null;
    BigInteger number94 = null;
    BigInteger number95 = null;
    BigInteger number96 = null;
    BigInteger number97 = null;
    BigInteger number98 = null;
    BigInteger number99 = null;
    BigInteger number100 = null;
    List<Integer> intList1 = null;
    List<Integer> intList2 = null;
    List<Integer> intList3 = null;
    List<Integer> intList4 = null;
    List<Integer> intList5 = null;
    List<Integer> intList6 = null;
    List<Integer> intList7 = null;
    List<Integer> intList8 = null;
    List<Integer> intList9 = null;
    List<Integer> intList10 = null;
    List<Integer> intList11 = null;
    List<Integer> intList12 = null;
    List<Integer> intList13 = null;
    List<Integer> intList14 = null;
    List<Integer> intList15 = null;
    List<Integer> intList16 = null;
    List<Integer> intList17 = null;
    List<Integer> intList18 = null;
    List<Integer> intList19 = null;
    List<Integer> intList20 = null;
    List<Integer> intList21 = null;
    List<Integer> intList22 = null;
    List<Integer> intList23 = null;
    List<Integer> intList24 = null;
    List<Integer> intList25 = null;
    List<Integer> intList26 = null;
    List<Integer> intList27 = null;
    List<Integer> intList28 = null;
    List<Integer> intList29 = null;
    List<Integer> intList30 = null;
    List<Integer> intList31 = null;
    List<Integer> intList32 = null;
    List<Integer> intList33 = null;
    List<Integer> intList34 = null;
    List<Integer> intList35 = null;
    List<Integer> intList36 = null;
    List<Integer> intList37 = null;
    List<Integer> intList38 = null;
    List<Integer> intList39 = null;
    List<Integer> intList40 = null;
    List<Integer> intList41 = null;
    List<Integer> intList42 = null;
    List<Integer> intList43 = null;
    List<Integer> intList44 = null;
    List<Integer> intList45 = null;
    List<Integer> intList46 = null;
    List<Integer> intList47 = null;
    List<Integer> intList48 = null;
    List<Integer> intList49 = null;
    List<Integer> intList50 = null;

    @Override
    public String toString() {
        return intList1 + "##" + number90;
    }

    public void changeValues() {
        this.intList1 = Arrays.asList(1234, 2242, 5122);
        this.number90 = BigInteger.valueOf(4355677);
    }
}
